In [92]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [93]:
#PHASE 1

In [ ]:
df = pd.read_csv('loan_default_dataset (1).csv')
df

,Customer_ID,Age,Gender,Marital_Status,Education_Level,Employment_Status,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Existing_Loans_Count,Debt_to_Income_Ratio,Payment_History,Savings_Balance,Loan_Purpose,Default
0,CUST00000,59,Male,Single,High School,Unemployed,153435,57032,36,337,0,0.16,Poor,3594,Car,1
1,CUST00001,49,Male,Single,Bachelor,Unemployed,1358590,753454,24,799,3,0.52,Average,77610,Business,1
2,CUST00002,35,Male,Married,Bachelor,Employed,864995,350178,60,342,1,0.22,Average,189727,Home,1
3,CUST00003,63,Male,Married,Master,Unemployed,862917,676946,12,816,1,0.66,Good,421647,Education,1
4,CUST00004,28,Female,Married,High School,Unemployed,525601,957555,24,367,1,0.23,Average,214756,Home,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST01995,54,Female,Married,PhD,Unemployed,523221,969156,36,881,2,0.13,Average,270189,Car,0
1996,CUST01996,38,Male,Married,Master,Employed,1184023,486841,48,832,2,0.53,Poor,306399,Car,1
1997,CUST01997,33,Male,Married,High School,Self-Employed,946060,308466,24,434,1,0.65,Average,52965,Education,1
1998,CUST01998,61,Female,Single,High School,Unemployed,543545,529198,60,410,4,0.31,Poor,264381,Personal,1
1999,CUST01999,43,Male,Divorced,Master,Self-Employed,450763,593028,12,582,0,0.16,Poor,393955,Car,1

In [ ]:
print("Shape of dataset:",df.shape)

Shape of dataset: (2000, 16)

In [ ]:
print("Size of dataset:",df.size)

Size of dataset: 32000

In [ ]:
#Understanding the structure of dataset
df.describe()

,Age,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Existing_Loans_Count,Debt_to_Income_Ratio,Savings_Balance,Default
count,2000.000000,2.000000e+03,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000
mean,42.694000,8.299711e+05,525997.057000,36.354000,596.964000,1.974500,0.400720,247342.831500,0.69550
std,12.614195,3.862774e+05,272378.273758,17.087442,171.731356,1.420161,0.171901,143678.727557,0.46031
min,21.000000,1.500370e+05,50799.000000,12.000000,300.000000,0.000000,0.100000,1056.000000,0.00000
25%,32.000000,5.106692e+05,296489.750000,24.000000,452.000000,1.000000,0.250000,124489.250000,0.00000
50%,43.000000,8.314425e+05,525436.000000,36.000000,593.000000,2.000000,0.400000,249331.000000,1.00000
75%,54.000000,1.153992e+06,770494.000000,48.000000,748.000000,3.000000,0.542500,369349.250000,1.00000
max,64.000000,1.499987e+06,999500.000000,60.000000,899.000000,4.000000,0.700000,499901.000000,1.00000

In [ ]:
#Counting total null values in each column using null function
print("Total null values in each column:",df.isna().sum())
#Counting total null values in dataset
print("Total null values in dataset:",df.isna().sum().sum())

Total null values in each column: Customer_ID             0
Age                     0
Gender                  0
Marital_Status          0
Education_Level         0
Employment_Status       0
Annual_Income           0
Loan_Amount             0
Loan_Term_Months        0
Credit_Score            0
Existing_Loans_Count    0
Debt_to_Income_Ratio    0
Payment_History         0
Savings_Balance         0
Loan_Purpose            0
Default                 0
dtype: int64
Total null values in dataset: 0

In [ ]:
#Checking for duplicates
print("Duplicated rows:",df.duplicated().sum())

Duplicated rows: 0

In [ ]:
#Checking necessary features needed
print("Column names:\n",df.columns)
df.head()

Column names:
 Index(['Customer_ID', 'Age', 'Gender', 'Marital_Status', 'Education_Level',
       'Employment_Status', 'Annual_Income', 'Loan_Amount', 'Loan_Term_Months',
       'Credit_Score', 'Existing_Loans_Count', 'Debt_to_Income_Ratio',
       'Payment_History', 'Savings_Balance', 'Loan_Purpose', 'Default'],
      dtype='object')

,Customer_ID,Age,Gender,Marital_Status,Education_Level,Employment_Status,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Existing_Loans_Count,Debt_to_Income_Ratio,Payment_History,Savings_Balance,Loan_Purpose,Default
0,CUST00000,59,Male,Single,High School,Unemployed,153435,57032,36,337,0,0.16,Poor,3594,Car,1
1,CUST00001,49,Male,Single,Bachelor,Unemployed,1358590,753454,24,799,3,0.52,Average,77610,Business,1
2,CUST00002,35,Male,Married,Bachelor,Employed,864995,350178,60,342,1,0.22,Average,189727,Home,1
3,CUST00003,63,Male,Married,Master,Unemployed,862917,676946,12,816,1,0.66,Good,421647,Education,1
4,CUST00004,28,Female,Married,High School,Unemployed,525601,957555,24,367,1,0.23,Average,214756,Home,1

In [ ]:
#Dropping columns which are not required
df=df.drop(columns = ['Customer_ID','Gender'])

In [ ]:
df

,Age,Marital_Status,Education_Level,Employment_Status,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Existing_Loans_Count,Debt_to_Income_Ratio,Payment_History,Savings_Balance,Loan_Purpose,Default
0,59,Single,High School,Unemployed,153435,57032,36,337,0,0.16,Poor,3594,Car,1
1,49,Single,Bachelor,Unemployed,1358590,753454,24,799,3,0.52,Average,77610,Business,1
2,35,Married,Bachelor,Employed,864995,350178,60,342,1,0.22,Average,189727,Home,1
3,63,Married,Master,Unemployed,862917,676946,12,816,1,0.66,Good,421647,Education,1
4,28,Married,High School,Unemployed,525601,957555,24,367,1,0.23,Average,214756,Home,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,54,Married,PhD,Unemployed,523221,969156,36,881,2,0.13,Average,270189,Car,0
1996,38,Married,Master,Employed,1184023,486841,48,832,2,0.53,Poor,306399,Car,1
1997,33,Married,High School,Self-Employed,946060,308466,24,434,1,0.65,Average,52965,Education,1
1998,61,Single,High School,Unemployed,543545,529198,60,410,4,0.31,Poor,264381,Personal,1
1999,43,Divorced,Master,Self-Employed,450763,593028,12,582,0,0.16,Poor,393955,Car,1

In [ ]:
#Scaling the features using StandardScaler
ss = StandardScaler()
standardized_data = pd.DataFrame(ss.fit_transform(df[['Annual_Income', 'Loan_Amount', 'Loan_Term_Months',
       'Credit_Score', 'Existing_Loans_Count', 'Debt_to_Income_Ratio', 'Savings_Balance', 'Default']]))

standardized_data

,0,1,2,3,4,5,6,7
0,-1.751864,-1.722172,-0.020722,-1.514162,-1.390683,-1.400691,-1.696909,0.661676
1,1.368838,0.835286,-0.723168,1.176760,0.722282,0.694061,-1.181631,0.661676
2,0.090693,-0.645657,1.384169,-1.485039,-0.686361,-1.051566,-0.401105,0.661676
3,0.085312,0.554327,-1.425614,1.275776,-0.686361,1.508687,1.213456,0.661676
4,-0.788154,1.584803,-0.723168,-1.339426,-0.686361,-0.993378,-0.226860,0.661676
...,...,...,...,...,...,...,...,...
1995,-0.794317,1.627405,-0.020722,1.654369,0.017960,-1.575254,0.159048,-1.511315
1996,0.916804,-0.143792,0.681724,1.368968,0.017960,0.752249,0.411132,0.661676
1997,0.300608,-0.798836,-0.723168,-0.949185,-0.686361,1.450500,-1.353203,0.661676
1998,-0.741689,0.011755,1.384169,-1.088973,1.426603,-0.527878,0.118615,0.661676
1999,-0.981944,0.246157,-1.425614,-0.087158,-1.390683,-1.400691,1.020672,0.661676

In [ ]:
#Naming standardized columns using rename function

print("Standardized Data:\n")

standardized_data.rename(columns={0:'Annual_Income',
1:'Loan_Amount',
2:'Loan_Term_Months',
3:'Credit_Score',
4:'Existing_Loan_Count',
5:'Debt_to_Income_Ratio',
6:'Savings_Balance',
7:'Default'},inplace = True)

standardized_data.head()

Standardized Data:

,Annual_Income,Loan_Amount,Loan_Term_Months,Credit_Score,Existing_Loan_Count,Debt_to_Income_Ratio,Savings_Balance,Default
0,-1.751864,-1.722172,-0.020722,-1.514162,-1.390683,-1.400691,-1.696909,0.661676
1,1.368838,0.835286,-0.723168,1.176760,0.722282,0.694061,-1.181631,0.661676
2,0.090693,-0.645657,1.384169,-1.485039,-0.686361,-1.051566,-0.401105,0.661676
3,0.085312,0.554327,-1.425614,1.275776,-0.686361,1.508687,1.213456,0.661676
4,-0.788154,1.584803,-0.723168,-1.339426,-0.686361,-0.993378,-0.226860,0.661676

In [95]:

#Using train test split
X = standardized_data.drop('Default',axis=1)
Y = standardized_data['Default']
Y

0       0.661676
1       0.661676
2       0.661676
3       0.661676
4       0.661676
          ...
1995   -1.511315
1996    0.661676
1997    0.661676
1998    0.661676
1999    0.661676
Name: Default, Length: 2000, dtype: float64

In [96]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [97]:
#PHASE 2